
<div class="col-lg-12">
    <div class="container">
        <div class="row" id="head">
        </div>
    </div>
</div>

<div class="col-lg-12">
    <div class="container">
        <div class="row" id="quote">
            <br />
            <h1 id="text">Movie Quiz</h1>
            <br />
            <hr class="linelong" />
            <br />
            <div>
                <a href="/moviequiz/show"><button type="button"  class="btn custom-btn" id="start"><p>Start Quiz</p></button></a>
                <a href="/moviequiz/quiz/new"><button type="button" class="btn custom-btn" id="add"><p >Add a question</p></button></a>
                <br />
                <a href="/moviequiz/quiz/view"><button type="button" class="btn custom-btn" id="view"><p>View Movies</p></button></a>
                <a><button type="button" class="btn custom-btn" id="search"><p></p></button></a>
            </div>
        </div>
    </div>
</div>
