<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="col-lg-12">
    <div class="container">
        <div class="row">
            <nav>
                <ul class="pager">
                    <li class="previous"><h4 id="time">Movie Quiz <span id="timeP"></span></h4></li>
                    <li class="next"><?php echo $this->tag->linkTo(["index", "Menu"]); ?></li>

                </ul>
            </nav>
        </div>

    </div>
</div>

<div class="col-lg-12">
    <div class="container">
        <div class="row" id="quote">
            <div class="col-sm-11">
                <br />
                <h2 id="text"><?php echo $quiz->quote; ?></h2>
                <div class="hidden" id="answer"><?php echo $quiz->movie; ?></div>
                <div class="hidden" id="answer-id"><?php echo $quiz->id; ?></div>
                <br />
                <hr class="linelong" />
                <br />
                <div>
                    <button type="button" class="btn custom-btn-play" id="<?php echo $answers[0]['id']; ?>"><p id ="A1"><?php echo $answers[0]['movie']; ?></p></button>
                    <button type="button" class="btn custom-btn-play" id="<?php echo $answers[1]['id']; ?>"><p id ="B1"><?php echo $answers[1]['movie']; ?></button>
                    <br />
                    <button type="button" class="btn custom-btn-play" id="<?php echo $answers[2]['id']; ?>"><p id ="C1"><?php echo $answers[2]['movie']; ?></p></button>
                    <button type="button" class="btn custom-btn-play" id="<?php echo $answers[3]['id']; ?>"><p id ="D1"><?php echo $answers[3]['movie']; ?></p></button>
                </div>
            </div>

            <div class="col-sm-1 hundred-height">
                <div class="row">
                    <div class="down-more">
                        <nav>
                            <ul class="pager hidden">
                                <li class="previous"><?php echo $this->tag->linkTo(["show", "", "class" => "fa fa-angle-double-right fa-5x"]); ?></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="container mt-2">
        <div class="row">
            <h3 id="extra" class="hidden"><?php echo $quiz->extra; ?></h3>
        </div>
    </div>
</div>
