<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["quiz/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Movie Number</th>
                <th>Quote</th>
                <th>Movie</th>
                <th>Movie Of Year</th>
                <th>Url</th>
                <th>Extra</th>
                <th>Edit</th>
                <th>Delete</th>                
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $quiz): ?>
            <tr>
                <td><?php echo $quiz->getId() ?></td>
                <td><?php echo $quiz->getQuote() ?></td>
                <td><?php echo $quiz->getMovie() ?></td>
                <td><?php echo $quiz->getMovieYear() ?></td>
                <td><a href="<?php echo $quiz->getUrl() ?>" target="_blank">IMDB</a></td>
                <td><?php echo $quiz->getExtra() ?></td>

                <td><?php echo $this->tag->linkTo(["quiz/edit/" . $quiz->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["quiz/delete/" . $quiz->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("quiz/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("quiz/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("quiz/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("quiz/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
