<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Movie Quiz Game</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
        <link rel="stylesheet" href="<?php echo $this->url->get('css/style.css')?>">

    </head>
    <body>
        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <!-- Custom appliation js  -->
        <?php echo \Phalcon\Tag::javascriptInclude("js/application.js"); ?>
        <!-- Welcome/index/index page js-->
        <?php echo \Phalcon\Tag::javascriptInclude("js/welcome.js"); ?>
        <!-- Quiz JS-->
        <?php echo \Phalcon\Tag::javascriptInclude("js/play.js"); ?>

    </body>
</html>
